/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-04 22:22:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reg;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SimpleRecipe/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SImpleRecipe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1587384150934L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입 페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" >\r\n");
      out.write("<script src=\"/resources/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"reg-wrap\">\r\n");
      out.write("\t<h2>회원가입</h2>\r\n");
      out.write("\t<p>Welcome to SimpleRecipe</p>\r\n");
      out.write("\t<form action=\"/register.do\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"reg-div reg-id-wrap\">\r\n");
      out.write("\t\t\t<label>ID</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"userTbId\" class=\"inputTxt\" required/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-pw-wrap\">\r\n");
      out.write("\t\t\t<label>PWD</label>\r\n");
      out.write("\t\t\t<input type=\"password\" id=\"pwd\" name=\"userTbPwd\" class=\"inputTxt\" required/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-pw-check-wrap\">\r\n");
      out.write("\t\t\t<label>PWD CHECK</label>\r\n");
      out.write("\t\t\t<input type=\"password\" id=\"pwd2\" name=\"userTbPwd2\" class=\"inputTxt\" required/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-name-wrap\">\r\n");
      out.write("\t\t\t<label>NAME</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"userTbName\" class=\"inputTxt\" required/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-gender-wrap\">\r\n");
      out.write("\t\t\t<label>GENDER</label>\r\n");
      out.write("\t\t\t<div class=\"reg-gender-inner-wrap\">\r\n");
      out.write("\t\t\t\t<label class=\"inputRadioLabel\" for=\"male-checked\">남</label><input type=\"radio\" name=\"userTbGender\" class=\"inputRadio\" id=\"male-checked\" value=\"M\" checked required/>\r\n");
      out.write("\t\t\t\t<label class=\"inputRadioLabel\" for=\"female-checked\">여</label><input type=\"radio\" name=\"userTbGender\" class=\"inputRadio\" id=\"female-checked\" value=\"F\" required/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-birth-wrap\">\r\n");
      out.write("\t\t\t<label>BIRTHDAY</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"birthday\" name=\"userTbBirthdayTemp\" class=\"inputTxt\" placeholder=\"                         예)2001-01-01\" required />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-email-wrap\">\r\n");
      out.write("\t\t\t<label>EMAIL</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"email\" name=\"userTbEmail\" class=\"inputTxt\" required/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"reg-div reg-phone-wrap\">\r\n");
      out.write("\t\t\t<label>PHONE</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"phone\" name=\"userTbPhone\" class=\"inputTxt\" placeholder=\"                         '-'없이 작성해주세요 예)01012345678\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"btn-wrap txt-c mt40\">\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"submitReg\" class=\"commonBtn\" >회원가입</button>\r\n");
      out.write("\t\t\t<a href=\"login.do\"><button type=\"button\" class=\"commonBtn\">취소</button></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#submitReg').click(function(){\r\n");
      out.write("\t\tvar pwd = $('#pwd').val();\r\n");
      out.write("\t\tvar pwd2 = $('#pwd2').val();\r\n");
      out.write("\t\tvar birthday = $('#birthday').val();\r\n");
      out.write("\t\tvar email = $('#email').val();\r\n");
      out.write("\t\tvar phone = $('#phone').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar regBirthdayExp = RegExp(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/);\r\n");
      out.write("\t\tvar regEmailExp = RegExp(/^[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*@[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*.[a-zA-Z]{2,3}$/);\r\n");
      out.write("\t\tvar regPhoneExp = RegExp(/^01(0|1|[6-9])([0-9]{3,4})([0-9]{4})$/);\r\n");
      out.write("\t\tif(pwd != pwd2){\r\n");
      out.write("\t\t\talert(\"비밀번호 2개가 불일치합니다.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 생년월일 데이터 처리\r\n");
      out.write("\t\tif(!regBirthdayExp.test(birthday)){\r\n");
      out.write("\t\t\talert(\"생년월일 형식에 맞춰 입력해주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 이메일 데이터 처리\r\n");
      out.write("\t\tif(!regEmailExp.test(email)){\r\n");
      out.write("\t\t\talert(\"이메일 형식에 맞춰 입력해주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t// 전화번호 데이터 처리\r\n");
      out.write("\t\tif(!regPhoneExp.test(phone)){\r\n");
      out.write("\t\t\talert(\"전화번호 형식에 맞춰 입력해주세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talert(\"회원가입 성공\");\r\n");
      out.write("\t\t$('form').submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".inputTxt\").on(\"focus\", function(){\r\n");
      out.write("\t\t$(this).siblings('label').css({\r\n");
      out.write("\t\t\t'left': '-16px',\r\n");
      out.write("\t\t\t'top' : '-42px',\r\n");
      out.write("\t\t\t'font-size' : '20px'\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".reg-birth-wrap .inputTxt\").on(\"focus\", function(){\r\n");
      out.write("\t\t$(this).attr('placeholder', '예)2001-01-01');\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".reg-phone-wrap .inputTxt\").on(\"focus\", function(){\r\n");
      out.write("\t\t$(this).attr('placeholder', \"'-'없이 작성해주세요 예)01012345678\");\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/reg/register.jsp(9,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/common.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/reg/register.jsp(10,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/register.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
